#!/usr/bin/env bash

## Script to take screenshots with grim, slurp (in Wayland)


time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$HOME/Pictures/Screenshots"  # need 
file="Screenshot_${time}_${RANDOM}.png"
screenie="${dir}/${file}"

# notify and view screenshoti
notify_cmd_shot="notify-send -h string:x-canonical-private-synchronous:shot-notify -u low -i ${screenie}"
notify_view () {
	${notify_cmd_shot} "Copied to clipboard."
	sxiv ${screenie}
    keep=$(echo -en "Delete\nSave" | rofi -dmenu -i -config ~/.config/rofi/screenshot.rasi)
	if [[ "$keep" == "Save" ]]; then
		${notify_cmd_shot} "Screenshot Saved."
	else
		${notify_cmd_shot} "Screenshot Deleted."
        rm -f "$screenie"
	fi
}

# take shots
shotnow () {
	cd ${dir} && grim - | tee "$file" | wl-copy
	notify_view
}

shotwin () {
	w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
	w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
	cd ${dir} && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
	notify_view
}

shotarea () {
    grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | satty --filename - --output-filename ~/Pictures/Screenshots/Screenshot_$time.png --init-tool brush --copy-command wl-copy 
	# cd ${dir} && grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | tee "$file" | wl-copy
	# notify_view
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--win" ]]; then
	shotwin
else
	echo -e "Available Options : --now --win --area"
fi

exit 0
