# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

boot = {
    kernelParams =
      [ "acpi_rev_override" "mem_sleep_default=deep" "intel_iommu=igfx_off" "nvidia-drm.modeset=1" ];
  };

  fileSystems."/mnt/NAS" = {
    device = "srv-prod-nas.home.USER_NAMEkiss.net:/mnt/Main Storage/USER_NAME/USER_NAME";
    fsType = "nfs";
  };


# Make sure opengl is enabled
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

# Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the KDE Desktop Environment.
  # services.xserver.displayManager.sddm.enable = true;
  #services.xserver.desktopManager.plasma5.enable = true;

  # ## NVIDIA 
  # services.xserver = {
  #   videoDrivers = [ "nvidia" ];

  #   config = ''
  #     Section "Device"
  #         Identifier  "Intel Graphics"
  #         Driver      "intel"
  #         #Option      "AccelMethod"  "sna" # default
  #         #Option      "AccelMethod"  "uxa" # fallback
  #         Option      "TearFree"        "true"
  #         Option      "SwapbuffersWait" "true"
  #         BusID       "PCI:02:0:0"
  #         #Option      "DRI" "2"             # DRI3 is now default
  #     EndSection

  #     Section "Device"
  #         Identifier "nvidia"
  #         Driver "nvidia"
  #         BusID "PCI:02:0:0"
  #         Option "AllowEmptyInitialConfiguration"
  #     EndSection
  #   '';
  #   screenSection = ''
  #     Option         "metamodes" "nvidia-auto-select +0+0 {ForceFullCompositionPipeline=On}"
  #     Option         "AllowIndirectGLXProtocol" "off"
  #     Option         "TripleBuffer" "on"
  #   '';
  # };


  # hardware.nvidia = {

  #   # Modesetting is needed for most wayland compositors
  #   modesetting.enable = true;

  #   # Use the open source version of the kernel module
  #   # Only available on driver 515.43.04+
  #   open = false;

  #   # Enable the nvidia settings menu
  #   nvidiaSettings = true;

  #   # Optionally, you may need to select the appropriate driver version for your specific GPU.
  #   package = config.boot.kernelPackages.nvidiaPackages.stable;
  # };
  #   hardware.nvidia.forceFullCompositionPipeline = true;

  # hardware.nvidia.prime = {
  #   # Sync Mode
  #   #sync.enable = true;
  #   # Offload Mode
  #   offload.enable = true;

  #   # Bus ID of the NVIDIA GPU. You can find it using lspci, either under 3D or VGA
  #   nvidiaBusId = "PCI:02:0:0";

  #   # Bus ID of the Intel GPU. You can find it using lspci, either under 3D or VGA
  #   intelBusId = "PCI:0:02:0";
  # };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/68af6772-6eb2-4a3c-8c35-7e56cab522c3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7D6B-E622";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f658bbed-6c16-44a8-b7de-ea56d6e2a716"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
