#!/usr/bin/env bash

dir="$HOME/Pictures/Screenshots/"

shotwin () {
	w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
	w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
	grim -g "$w_pos $w_size" -|  satty --filename - 
}

shotarea () {
    grim -g "$(slurp -b 1B1F28CC -c C778DD0D -s C778DD0D -w 2)" - | satty --filename -
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--win" ]]; then
	shotwin
else
	echo -e "Available Options : --win --area"
fi

exit 0
