#!/usr/bin/env bash

## Script to take screenshots with grim, slurp (in Wayland)


time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$HOME/Pictures/Screenshots"  # need 
file="Screenshot_${time}_${RANDOM}.png"
screenie="${dir}/${file}"

# notify and view screenshoti
notify_cmd_shot="notify-send -h string:x-canonical-private-synchronous:shot-notify -u low -i ${screenie}"

# take shots
shotnow () {
	cd ${dir} && grim - | tee "$file" | wl-copy
}

shotwin () {
	w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
	w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
	grim -g "$w_pos $w_size" -|  satty --filename - --output-filename ~/Pictures/Screenshots/Screenshot_$time.png --init-tool brush --copy-command wl-copy 
}

shotarea () {
    grim -g "$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2)" - | satty --filename - --output-filename ~/Pictures/Screenshots/Screenshot_$time.png --init-tool brush --copy-command wl-copy 
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--win" ]]; then
	shotwin
else
	echo -e "Available Options : --now --win --area"
fi

exit 0
