#!/usr/bin/env bash
## Get Volume
BRed='\033[1;31m'
BPurple='\033[1;35m'      # Purple
NoColor="\033[0m"
BGreen='\033[1;32m'       # Green

output_dev=$(wpctl status |sed -n '/├─ Sinks/,/├─/p'|grep "\*" |awk '{print $3 }' |sed 's/\.//g')
input_dev=$(wpctl status |grep Audio -A 10|grep Sources -A 6 |grep "\*" |awk '{print $3 }' |sed 's/\.//g')
# echo $output_dev $input_dev
get_vol() {
	while true; do
  	wpctl get-volume $output_dev | grep '^Volume:' |sed -e 's/0\.//g' -e's/\.//g' | grep -oE '[0-9]{2,3}' 
	sleep 1
	done
}

## Set Volume
set_vol() {
  wpctl set-volume $output_dev $1"%"
}

## Toggle Volume
toggle_vol() {
  wpctl set-mute $output_dev toggle
}

## Get Volume Icon
# TODO: different icons according to volume level, maybe
get_volicon() {
	while true; do
		MUTE="$(wpctl status |grep "$output_dev" |grep -o 'MUTED')"
		VOL="$(wpctl get-volume $output_dev | rg '^Volume:' |sed -e 's/0\.//g' -e's/\.//g' | rg -o '[0-9]{2,3}')"
		if [[ "$MUTE" == "MUTED" ]]; then
			echo " "
		else
			if [[ "$VOL" -le 30 ]]; then
				echo "󱄡"
			elif [[ "$VOL" -le 75 ]]; then
				echo ""
			elif [[ "$VOL" -le 100 ]]; then
				echo ""
			else
				echo ""
			fi
				
		fi
		sleep 1
	done
}

## Get Mic Icon
get_micicon() {
	while true; do
  	MUTE="$(wpctl status |grep "\*"|grep $input_dev |grep -o 'MUTED')"
    # echo $MUTE
  	if [[ "${MUTE}" == "MUTED" ]]; then
    	echo ""
  	else
	 		echo ""
  	fi
		sleep 2
	done
}

## Toggle Mic
toggle_mic() {
  wpctl set-mute $input_dev toggle
}

## Get Mic
get_mic() {
	while true; do
  	wpctl get-volume $input_dev | grep '^Volume:' | grep -oE '[0-9]{2}' 
		sleep 1
	done
}

## Set Mic
set_mic() {
  wpctl set-volume $input_dev $1"%"
}




if [[ "$1" == "--set-vol" ]]; then
	set_vol "$2"
elif [[ "$1" == "--get-vol" ]]; then
	get_vol
elif [[ "$1" == "--toggle-vol" ]]; then
	toggle_vol
elif [[ "$1" == "--get-volicon" ]]; then
	get_volicon
elif [[ "$1" == "--get-micicon" ]]; then
	get_micicon
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-mic" ]]; then
	get_mic
elif [[ "$1" == "--set-mic" ]]; then
	set_mic "$2"
else
  printf "${BRed}[ERROR]${BPurple} Please use one of the following flags ${BGreen}\n--set-vol, --get-vol, --toggle-vol,\n--get-volicon, --get-micicon, --toggle-mic,\n--get-mic, --set-mic${BPurple}. Thank you.${NoColor}"
fi

