{pkgs, lib, config, inputs, ... }:
{
	home.packages = with pkgs; [
		wl-clipboard
		grim
		slurp
    	swww
    	rofi-wayland
	    waybar
	];
  wayland.windowManager.hyprland = {
    enable = true;
    package = inputs.hyprland.packages.${pkgs.system}.hyprland;
    # No longer exists as it is not necessary.
    # enableNvidiaPatches = true;
    xwayland.enable = true;
    extraConfig = /*bash*/ ''
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################
#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#
#autogenerated = 1 # remove this line to remove the warning
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-1,2560x1080@200,0x-1080,1,vrr,1
monitor=DP-2,2560x1080@200,0x0,1,vrr,1
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/window_rules.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/workspaces.conf
# Some default env vars.
env = XCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = SUDO_ASKPASS, $HOME/.local/bin/dmenupass
env = NIXPKGS_ALLOW_UNFREE,1
# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_rules =
    # kb_options = caps:Super_L
    follow_mouse = 1
    accel_profile = flat
    force_no_accel = true
    touchpad {
        natural_scroll = no
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    # gaps_in = 5
    # gaps_out = 15
    border_size = 3 
    col.active_border = rgb(711C91) rgb(EA00D9) rgb(0abdc6) 45deg
    col.inactive_border = rgb(133e7c) rgb(091833) 45deg
    layout = dwindle
    allow_tearing = false
}
env = WLR_DRM_NO_ATOMIC,1
decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    # blur_ignore_opacity = true
    rounding = 10
    drop_shadow = yes
    blur {
      enabled = true
      size = 12
      passes = 3
      new_optimizations = on
      noise = 0.05
      ignore_opacity = true
    }
    # fullscreen_opacity = 0.7
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}
animations { #Thank you to HyprDots
    enabled = yes
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = 0
    preserve_split = 1
    force_split = 2
}
master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}
gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
}
binds {
   allow_workspace_cycles = yes
}
# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -0.5
}
misc {
  # force_hypr_chan = true
  mouse_move_enables_dpms = true
}
blurls = dashboard
    '';
  };
  home.file."${config.xdg.configHome}/hypr/scripts" = {
    source = ./scripts;
    recursive = true;
  };
  home.file."${config.xdg.configHome}/hypr/binds.conf".text = /* hyprlang  */ ''
$mainMod = SUPER
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

bind = ALT, escape, fakefullscreen
bind = $mainMod, Return, exec, ${pkgs.kitty}/bin/kitty
bind = $mainMod, O, killactive, 
bind = $mainMod SHIFT, D, exec, ps aux |rg [d]iscord | awk '{ print $2 }' |xargs kill
bind = $mainMod, M, exit,
bind = $mainMod, N, exec, ${pkgs.swaynotificationcenter}/bin/swaync-client -t
bind = $mainMod, R, exec,hyprctl reload
bind = $mainMod, E, exec, ~/.local/bin/dmenuunicode
bind = $mainMod, V, exec, ${pkgs.youtube-music}/bin/youtube-music --disable-gpu 
bind = $mainMod, G, exec, ~/.config/hypr/scripts/gamelauncher.sh 2
# bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, I, exec, ~/.scripts/scrn_record.sh
bind = $mainMod, C, exec, ${pkgs.kitty}/bin/kitty ${pkgs.helix}/bin/hx ~/.dotfiles/nixos
# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
# Move Windows
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d
# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
# Enable Floating on Windows
bind = $mainMod SHIFT, space,togglefloating
# Discord PPT 
bind = ,Insert,pass,^(.*discord*.)$

# FKey binds
bind = $mainMod, F1, exec, ~/.config/hypr/scripts/show_binds.sh
bind = $mainMod, F2, exec, ~/.local/bin/dmenumount
bind = $mainMod, F3, exec, ~/.local/bin/dmenuumount

# Other
bind = $mainMod, T, exec, ${pkgs.xfce.thunar}/bin/thunar
bind = $mainMod, B, exec, ${pkgs.kitty}/bin/kitty ${pkgs.btop}/bin/btop
bind = $mainMod, H, exec, $HOME/.config/eww/scripts/eww-start.sh &
# Kill discord
bind = $mainMod SHIFT, D, exec, \'\'ps aux | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} [d]iscord | awk '{ print $2 }' | xargs kill\'\'

# bind = $mainMod, U, exec, brave
bind = $mainMod, U, exec, ${pkgs.firefox}/bin/firefox
bind = $mainMod, D, exec, ~/.config/rofi/launchers/launcher.sh
bind = ALT, space, exec, ~/.config/rofi/launchers/launcher.sh
bind = $mainMod, Y, exec, ~/.local/bin/yt
bind = $mainMod,F,fullscreen
bind = $mainMod,TAB,workspace,previous
bind = $mainMod SHIFT,s,exec, ~/.config/hypr/scripts/screenshot --area
bind = $mainMod,x,exec, ${pkgs.wlogout}/bin/wlogout
# bind = $mainMod,x,exec, ~/.config/rofi/powermenu/powermenu.sh
bind = $mainMod,l,exec, ~/.config/hypr/scripts/locker.sh
  '';
  home.file."${config.xdg.configHome}/hypr/startup.conf".text = /* bash  */ ''
exec = bash $HOME/.config/hypr/scripts/hypronstart.sh
exec-once = ${pkgs.swww}/bin/swww init
# exec = $HOME/.scripts/background/cron.sh ~/Pictures/Space/
exec-once = ${pkgs.discord}/bin/discord &
# exec-once = /etc/profiles/per-user/USER_NAME/bin/brave
exec-once = ${pkgs.firefox}/bin/firefox &
# exec-once = ~/.config/hypr/scripts/sleep.sh & #Systemctl service works now for some reason
exec = sleep 1 ; bash $HOME/.config/eww/scripts/eww-start.sh &
exec = sleep 0.5 ; ${pkgs.eww-wayland}/bin/eww -c ~/.config/eww/bar close bar; ${pkgs.eww-wayland}/bin/eww -c ~/.config/eww/bar open bar &
  '';
  home.file."${config.xdg.configHome}/hypr/window_rules.conf".text = /* bash */ ''
# Example windowrule v1
windowrule = float, ^(pavucontrol)$
windowrulev2 = float, class:^(.*desktop-portal-gtk.*)$
windowrule = opacity 0.8 0.7, obsidian
# windowrule = opacity 0.8 0.7, brave-browser
# windowrulev2 = opacity 0.8 0.7, class:discord
windowrulev2 = opacity 1.0 1.0, title:^(.*YouTube.*)$
# windowrulev2 = float, class:^(*.steam_app.*)$
windowrulev2 = fullscreen, class:^(*.steam_app.*)$
windowrulev2 = opacity 1.0 1.0 , class:^(*.steam_app.*)$
windowrulev2 = float, class:(steam)
windowrulev2 = tile, class:(steam),title:^(.*Steam.*)$
windowrulev2 = size 842 465, class:thunar
windowrulev2 = opacity 0.83 0.83, class:thunar
windowrulev2 = opacity 0.95 0.93, title:^(.*nvim.*)$
windowrulev2 = float,class:^(thunar)$
windowrulev2 = size 842 465, class:Thunar
windowrulev2 = opacity 0.83 0.83, class:Thunar
windowrulev2 = float,class:^(Thunar)$


# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# App Workspace Bindings
windowrule = workspace 1, ^(.*firefox.*)$
# windowrule = workspace 1, ^(.*brave.*)$
windowrulev2 = workspace 3, class:^(.*steam_app.*)$
windowrule = workspace 9, ^(.*mpv.*)$
windowrule = workspace 7, ^(.*discord.*)$
windowrulev2 = workspace 6, class:^(.*YouTube Music.*)$
# XWaylandBridge
windowrulev2 = opacity 0.75 0.6, class:^.*kitty.*$
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
# Fix steam menu
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$

# Idle Inhibit

windowrulev2 = idleinhibit focus, title:.*(yuzu).*
windowrulev2 = idleinhibit focus, class:.*(steam_app).*
windowrulev2 = idleinhibit always, class:firefox,title:^(.*S[0-9].*E[0-9].*)$
windowrulev2 = idleinhibit always, class:firefox,title:^(.*YouTube.*)$
  '';
  home.file."${config.xdg.configHome}/hypr/workspaces.conf".text = /* bash  */ ''
# Workspace Binding.
workspace = 1,monitor:DP-2,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 2,monitor:DP-2,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 3,monitor:DP-2,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 4,monitor:DP-2,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 5,monitor:DP-2,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 6,monitor:DP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 7,monitor:DP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 8,monitor:DP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 9,monitor:DP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 10,monitor:DP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
 '';
}
