#!/bin/sh

toggle() {
    STATUS="$(bluetoothctl show | grep Powered | awk '{print $2}')"
    if [ $STATUS == "yes" ]; then
        bluetoothctl power off
        notify-send --icon=bluetooth-offline --urgency=normal "Bluetooth" "Bluetooth has been turned off."
    else
        bluetoothctl power on
        notify-send --icon=volume-level-high --urgency=normal "Bluetooth" "Bluetooth has been turned on."
    fi
}

icon() {
        # not connected
        if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
                echo "󰂲"
        else
                # on
                if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]; then
                        echo "󰂯"
                else
                        echo "󰂱"
                fi
        fi
}

status() {
        # not connected
        if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
                echo "Off"
        else
                # on
                if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]; then
                        echo "On"
                else
                        # get device alias
                        DEVICE=`echo info | bluetoothctl | grep 'Alias:' | awk -F:  '{ print $2 }'`
                        echo "$DEVICE"
                fi
        fi
}

battery() {
        mac_address=$(bluetoothctl info | grep "Device" | awk '{print $2}')

        # not connected
        # if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
        #         echo "Currently Off"
        # else
        #         # on
        #         if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]; then
        #                 echo "Not Connected"
        #         else
                        BATTERY=$(echo -e "info $mac_address" | bluetoothctl | grep "Battery" | awk '{print $4}' | tr -d '()')
                        echo "$BATTERY"
        #         fi
        # fi
}


if [[ $1 == "--status" ]]; then
        status
elif [[ $1 == "--icon" ]]; then
        icon
elif [[ $1 == "--toggle" ]]; then
        toggle
elif [[ $1 == "--battery" ]]; then
    battery
fi