#!/bin/sh

## Airplane Mode, Keyboard Brightness, DND Status 
AIRPLANESTATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"
DNDSTATUS=$(dunstctl is-paused)

# initialize/update airplane status/icon
if [[ $AIRPLANESTATUS == "no" ]]; then
    eww -c ~/.config/eww/fast-control-menu update airplane-status="Off"
    eww -c ~/.config/eww/fast-control-menu update airplane-icon="󰀞"
else
    eww -c ~/.config/eww/fast-control-menu update airplane-status="On"
    eww -c ~/.config/eww/fast-control-menu update airplane-icon="󰀝"
fi

# initialize dnd
if [ $DNDSTATUS == "false" ]; then
    eww -c ~/.config/eww/fast-control-menu update dnd-status="Off"
else
    eww -c ~/.config/eww/fast-control-menu update dnd-status="On"
fi

echo ""