#!/usr/bin/env bash


## Get Battery 
BRed='\033[1;31m'
BPurple='\033[1;35m'      # Purple
NoColor="\033[0m"
BGreen='\033[1;32m'       # Green

get_percentage() {
  while true; do
    # BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1) #For laptop
    BAT="hidpp_battery_0"
    echo "$(cat /sys/class/power_supply/${BAT}/capacity)"
    sleep 3
  done
}

## Get Battery Icon
get_icon() {
  while true; do
    BAT="hidpp_battery_0"
    # BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)
    BATSTATUS="$(cat /sys/class/power_supply/${BAT}/status)"
    BATVAL="$(cat /sys/class/power_supply/${BAT}/capacity)"

    if [[ "$BATSTATUS" == "Discharging" ]];then
      name="🖱️"
      if [ "$BATVAL" -gt 90 ];then
        echo ""
      elif [ "$BATVAL" -ge 80 ];then
        echo ""
      elif [ "$BATVAL" -ge 70 ];then
        echo ""
      elif [ "$BATVAL" -ge 60 ];then
        echo ""
      elif [ "$BATVAL" -ge 50 ];then
        echo ""
      elif [ "$BATVAL" -ge 40 ];then
        echo ""
      elif [ "$BATVAL" -ge 30 ];then
        echo ""
      elif [ "$BATVAL" -ge 20 ];then
        echo ""
      elif [ "$BATVAL" -ge 10 ];then
        echo ""
      elif [ "$BATVAL" -ge 0 ];then
        echo ""
      fi
     else
      echo ""
    fi
    sleep 3
  done
}


if [[ "$1" == "--perc" ]]; then
	get_percentage
elif [[ "$1" == "--icon" ]]; then
	get_icon taco
else
  printf "${BRed}[ERROR]${BPurple} Please use one of the following flags ${BGreen}\n--set-vol, --get-vol${BPurple} Thank you!${NoColor}"
fi


